table 'DataGEMS & MathE Example of questions and answers'
	lineageTag: e5750310-874e-4865-a11c-9b6a3cc7d213

	column 'Indicate your academic position:'
		dataType: string
		lineageTag: 3da0a5d4-166b-4a22-b12c-d4fa2587ac38
		summarizeBy: none
		sourceColumn: Indicate your academic position:

		annotation SummarizationSetBy = Automatic

	column 'What questions would you like to ask the DataGEMS Chat about general topics or the data you have uploaded (if applicable)?'
		dataType: string
		lineageTag: 628b5e55-1843-476a-869b-acc60ef92683
		summarizeBy: none
		sourceColumn: What questions would you like to ask the DataGEMS Chat about general topics or the data you have uploaded (if applicable)?

		annotation SummarizationSetBy = Automatic

	column 'What answer do you expect from this Chat? What topics should this answer address?'
		dataType: string
		lineageTag: 37c0b93a-6005-4686-9eb6-d64bfbf966fd
		summarizeBy: none
		sourceColumn: What answer do you expect from this Chat? What topics should this answer address?

		annotation SummarizationSetBy = Automatic

	partition 'DataGEMS & MathE Example of questions and answers' = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\murar\Desktop\Tesi\MathE\datasets\DataGEMS & MathE Example of questions and answers.xlsx"), null, true),
				    #"Questions and Answers_Sheet" = Origine{[Item="Questions and Answers",Kind="Sheet"]}[Data],
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Questions and Answers_Sheet",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(#"Modificato tipo", [PromoteAllScalars=true]),
				    #"Modificato tipo1" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"Indicate your academic position:", type text}, {"What questions would you like to ask the DataGEMS Chat about general topics or the data you have uploaded (if applicable)?", type text}, {"What answer do you expect from this Chat? What topics should this answer address?", type text}})
				in
				    #"Modificato tipo1"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

