table Keyword_Information
	lineageTag: fb99b905-105b-4f0e-ace8-a38b0190ca66

	column id
		dataType: int64
		formatString: 0
		lineageTag: ebd0fa32-3a46-423f-8cdd-1f7fc297640d
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column keyword
		dataType: string
		lineageTag: 8e4b0886-65a4-4da2-9401-78c9fbfe65f6
		summarizeBy: none
		sourceColumn: keyword

		annotation SummarizationSetBy = Automatic

	column Associated_Questions
		dataType: int64
		formatString: 0
		lineageTag: 245c0ad5-2726-406e-bd23-396c1dd82e0a
		summarizeBy: sum
		sourceColumn: Associated_Questions

		annotation SummarizationSetBy = Automatic

	column Topic
		dataType: string
		lineageTag: 333d5dfd-ce69-40e0-8206-cd83d60b2cd2
		summarizeBy: none
		sourceColumn: Topic

		annotation SummarizationSetBy = Automatic

	column Subtopic
		dataType: string
		lineageTag: b55b718a-9545-4be6-b6e5-2acfc9f31055
		summarizeBy: none
		sourceColumn: Subtopic

		annotation SummarizationSetBy = Automatic

	column countTeachingMaterials
		dataType: int64
		formatString: 0
		lineageTag: 72dc49b1-8567-4da4-a251-58cf7d2f74ce
		summarizeBy: sum
		sourceColumn: countTeachingMaterials

		annotation SummarizationSetBy = Automatic

	column countVideos
		dataType: int64
		formatString: 0
		lineageTag: 71c2690f-a6aa-4503-9c56-3e168a9f7847
		summarizeBy: sum
		sourceColumn: countVideos

		annotation SummarizationSetBy = Automatic

	partition Keyword_Information = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\murar\Desktop\Tesi\MathE\datasets\Keyword_Information.xlsx"), null, true),
				    Sheet1_Sheet = Origine{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"id", Int64.Type}, {"keyword", type text}, {"Associated_Questions", Int64.Type}, {"Topic", type text}, {"Subtopic", type text}, {"countTeachingMaterials", Int64.Type}, {"countVideos", Int64.Type}})
				in
				    #"Modificato tipo"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

