table MathE_LLManswers
	lineageTag: 171cfd6e-bc93-4e97-9ee7-00bbbf144a0e

	column id
		dataType: int64
		formatString: 0
		lineageTag: b809397c-ce57-42ef-86f2-0d779af32d33
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column question
		dataType: string
		lineageTag: 4e5203ef-f4e7-4edf-b724-ef4704311a15
		summarizeBy: none
		sourceColumn: question

		annotation SummarizationSetBy = Automatic

	column Manu_Correct_Answer
		dataType: int64
		formatString: 0
		lineageTag: c3a35434-2be0-4fce-9e00-285e5736c6aa
		summarizeBy: sum
		sourceColumn: Manu_Correct_Answer

		annotation SummarizationSetBy = Automatic

	column DeepSeek_Correct_Answer
		dataType: int64
		formatString: 0
		lineageTag: 79637b78-9dbb-44c0-b75e-f95b84ac0d76
		summarizeBy: sum
		sourceColumn: DeepSeek_Correct_Answer

		annotation SummarizationSetBy = Automatic

	column Topic
		dataType: string
		lineageTag: b2a216fb-df3b-4bba-b6f2-9605860e06c9
		summarizeBy: none
		sourceColumn: Topic

		annotation SummarizationSetBy = Automatic

	column Subtopic
		dataType: string
		lineageTag: 9e2c002c-4c86-4598-a9ed-5376eff9938a
		summarizeBy: none
		sourceColumn: Subtopic

		annotation SummarizationSetBy = Automatic

	column LecturerLevel
		dataType: int64
		formatString: 0
		lineageTag: 78b77000-bc39-4d4c-9b01-ef0159a65cee
		summarizeBy: sum
		sourceColumn: LecturerLevel

		annotation SummarizationSetBy = Automatic

	column algorithmLevel
		dataType: int64
		formatString: 0
		lineageTag: 24c30ee5-3a5e-4b55-a410-c1dd890b9f73
		summarizeBy: sum
		sourceColumn: algorithmLevel

		annotation SummarizationSetBy = Automatic

	column Manus_Right
		dataType: int64
		formatString: 0
		lineageTag: d0cab691-6595-4524-8000-c9d49f9e8aca
		summarizeBy: sum
		sourceColumn: Manus_Right

		annotation SummarizationSetBy = Automatic

	column DeepSeek_Right
		dataType: int64
		formatString: 0
		lineageTag: 38bd7b92-0280-4528-926d-5ca9bb57f73e
		summarizeBy: sum
		sourceColumn: DeepSeek_Right

		annotation SummarizationSetBy = Automatic

	partition MathE_LLManswers = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\murar\Desktop\Tesi\MathE\datasets\MathE_LLManswers.xlsx"), null, true),
				    Sheet1_Sheet = Origine{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"id", Int64.Type}, {"question", type text}, {"Manu_Correct_Answer", Int64.Type}, {"DeepSeek_Correct_Answer", Int64.Type}, {"Topic", type text}, {"Subtopic", type text}, {"LecturerLevel", Int64.Type}, {"algorithmLevel", Int64.Type}, {"Manus_Right", Int64.Type}, {"DeepSeek_Right", Int64.Type}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type text}}),
				    #"Rimosse colonne" = Table.RemoveColumns(#"Modificato tipo",{"Column11", "Column12", "Column13", "Column14"})
				in
				    #"Rimosse colonne"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

