table MathE_public
	lineageTag: c8e5dd68-0fe4-45e5-895d-b9ad69af2871

	column 'Student ID'
		dataType: int64
		formatString: 0
		lineageTag: 5b425a7e-68c9-45b9-84ba-331bc7878843
		summarizeBy: count
		sourceColumn: Student ID

		annotation SummarizationSetBy = Automatic

	column 'Student Country'
		dataType: string
		lineageTag: b2c7096d-0678-45e7-a4f1-d687f58d3448
		summarizeBy: none
		sourceColumn: Student Country

		annotation SummarizationSetBy = Automatic

	column 'Question ID'
		dataType: int64
		formatString: 0
		lineageTag: cae5241e-4368-40b8-ac8b-c0e340d129c2
		summarizeBy: none
		sourceColumn: Question ID

		annotation SummarizationSetBy = Automatic

	column 'Type of Answer'
		dataType: int64
		formatString: 0
		lineageTag: 4095a819-8642-43e5-bd8d-f08e9d24fb1b
		summarizeBy: sum
		sourceColumn: Type of Answer

		annotation SummarizationSetBy = Automatic

	column 'Question Level'
		dataType: string
		lineageTag: 4e8efb51-0050-4fdc-8e59-8a4059722fbc
		summarizeBy: none
		sourceColumn: Question Level

		annotation SummarizationSetBy = Automatic

	column Topic
		dataType: string
		lineageTag: 6239a5e8-c99e-4784-973b-174a396eed76
		summarizeBy: none
		sourceColumn: Topic

		annotation SummarizationSetBy = Automatic

	column Subtopic
		dataType: string
		lineageTag: 4611f1ce-bc3f-4e19-a6c1-8d6c320f6a5f
		summarizeBy: none
		sourceColumn: Subtopic

		annotation SummarizationSetBy = Automatic

	column Keywords
		dataType: string
		lineageTag: 6fd2dfed-e9ea-48a8-bd6f-45b31fbadccd
		summarizeBy: none
		sourceColumn: Keywords

		annotation SummarizationSetBy = Automatic

	partition MathE_public = m
		mode: import
		source =
				let
				    Origine = Csv.Document(File.Contents("C:\Users\murar\Desktop\Tesi\MathE\datasets\MathE_public.csv"),[Delimiter=";", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(Origine, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"Student ID", Int64.Type}, {"Student Country", type text}, {"Question ID", Int64.Type}, {"Type of Answer", Int64.Type}, {"Question Level", type text}, {"Topic", type text}, {"Subtopic", type text}, {"Keywords", type text}})
				in
				    #"Modificato tipo"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

