table platform_materials-1
	lineageTag: b0886728-7048-4677-8dd8-8c814044e7a8

	column material_id
		dataType: int64
		formatString: 0
		lineageTag: 70782904-0a7c-44f2-b519-baacd0b43943
		summarizeBy: sum
		sourceColumn: material_id

		annotation SummarizationSetBy = Automatic

	column keywords
		dataType: string
		lineageTag: 372f2e5f-8e88-4173-9a1b-a2cb8f03833a
		summarizeBy: none
		sourceColumn: keywords

		annotation SummarizationSetBy = Automatic

	partition platform_materials-1 = m
		mode: import
		source =
				let
				    Origine = Csv.Document(File.Contents("C:\Users\murar\Desktop\Tesi\MathE\platform_materials-1.csv"),[Delimiter=";", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(Origine, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"material_id", Int64.Type}, {"keywords", type text}}),
				    #"Filtrate righe" = Table.SelectRows(#"Modificato tipo", each ([material_id] <> null))
				in
				    #"Filtrate righe"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

