table Questions_Information
	lineageTag: 9fe564ab-b184-4983-b84a-18f59ac762a7

	column id
		dataType: int64
		formatString: 0
		lineageTag: 97ec1abc-8353-4806-aada-66a71124327a
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column question
		dataType: string
		lineageTag: f56a94b7-de8c-406d-8e50-7ed39cc8888c
		summarizeBy: none
		sourceColumn: question

		annotation SummarizationSetBy = Automatic

	column algorithmLevel
		dataType: int64
		formatString: 0
		lineageTag: 77d74269-93f3-45c9-868f-c59c4f0db53a
		summarizeBy: sum
		sourceColumn: algorithmLevel

		annotation SummarizationSetBy = Automatic

	column validate
		dataType: int64
		formatString: 0
		lineageTag: fbab16a2-20be-4481-9019-e97b70789048
		summarizeBy: sum
		sourceColumn: validate

		annotation SummarizationSetBy = Automatic

	column Validator
		dataType: string
		lineageTag: 6224229e-297c-440f-89f9-21770321a261
		summarizeBy: none
		sourceColumn: Validator

		annotation SummarizationSetBy = Automatic

	column Topic
		dataType: string
		lineageTag: e697ce68-ed8b-4488-a96a-485ec46860c8
		summarizeBy: none
		sourceColumn: Topic

		annotation SummarizationSetBy = Automatic

	column Correct
		dataType: string
		lineageTag: 24645732-9f14-4ff1-9162-2991e6c5e7fb
		summarizeBy: none
		sourceColumn: Correct

		annotation SummarizationSetBy = Automatic

	column Incorrect1
		dataType: string
		lineageTag: 92b367a1-51c0-490a-8029-03931e023e8c
		summarizeBy: none
		sourceColumn: Incorrect1

		annotation SummarizationSetBy = Automatic

	column Incorrect2
		dataType: string
		lineageTag: 4c28ec0a-ba84-4f69-9717-e154d21e88e7
		summarizeBy: none
		sourceColumn: Incorrect2

		annotation SummarizationSetBy = Automatic

	column Incorrect3
		dataType: string
		lineageTag: 4a5ff964-315c-4bc2-a84c-5f761261744f
		summarizeBy: none
		sourceColumn: Incorrect3

		annotation SummarizationSetBy = Automatic

	column LecturerLevel
		dataType: int64
		formatString: 0
		lineageTag: 3cf86c4c-9b91-4860-9d6e-baee457eaf38
		summarizeBy: sum
		sourceColumn: LecturerLevel

		annotation SummarizationSetBy = Automatic

	column Subtopic
		dataType: string
		lineageTag: 3a0e8463-24fd-46b8-ba04-60b603118a4f
		summarizeBy: none
		sourceColumn: Subtopic

		annotation SummarizationSetBy = Automatic

	column countMaterials
		dataType: int64
		formatString: 0
		lineageTag: 661d5cd0-3de8-4352-95c9-5fcf29d4f8bf
		summarizeBy: sum
		sourceColumn: countMaterials

		annotation SummarizationSetBy = Automatic

	column countVideos
		dataType: int64
		formatString: 0
		lineageTag: 22b37ad4-84ba-463e-aaee-d99f69fe00ea
		summarizeBy: sum
		sourceColumn: countVideos

		annotation SummarizationSetBy = Automatic

	column Author
		dataType: string
		lineageTag: e11e3d11-7ad7-4b4b-aed5-32de88c2c14b
		summarizeBy: none
		sourceColumn: Author

		annotation SummarizationSetBy = Automatic

	partition Questions_Information = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\murar\Desktop\Tesi\MathE\datasets\Questions_Information.xlsx"), null, true),
				    Sheet1_Sheet = Origine{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"id", Int64.Type}, {"question", type text}, {"algorithmLevel", Int64.Type}, {"validate", Int64.Type}, {"Validator", type text}, {"Topic", type text}, {"Correct", type text}, {"Incorrect1", type text}, {"Incorrect2", type text}, {"Incorrect3", type text}, {"LecturerLevel", Int64.Type}, {"Subtopic", type text}, {"countMaterials", Int64.Type}, {"countVideos", Int64.Type}, {"Author", type text}})
				in
				    #"Modificato tipo"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

